#%RAML 1.0 DataType

type: object
properties: 
  ID?: integer
  airline: string
  flightCode: string
  fromAirportCode: string
  toAirportCode: string
  departureDate: string
  emptySeats: integer
  totalSeats?: integer
  price: number
  planeType?: string