#%RAML 1.0
title: Jenkins Demo Flights API
version: 1.0

types: 
  Flight: !include datatypes/Flight.raml
  
/flights:
  get:
    displayName: Get flights
    queryParameters:
      code:
        displayName: Destination airport code
        required: false
        enum: 
          - SFO
          - LAX
          - PDX
          - CLE
          - PDF
      airline:
        displayName: Airline
        required: false
        enum: 
          - united
          - delta
          - american
    responses:
      200:
        body:
          application/json:
            type: Flight[]
            example: !include examples/FlightsExample.raml
                   
  post:
    body: 
      application/json:
        type: Flight
        example: !include examples/FlightNoIDExample.raml
    responses: 
      201:
        body: 
          application/json:
            example:
              message: Flight added (but not really)
